# ColossusX dependency audit stage, 2026-09-21. The full Dockerfile contains this same stage.
# ColossusX modifications, 2026-09-21: pinned Node, GPL source identity and bounded build memory.
# *****************************
# *** STAGE 1: Dependencies ***
# *****************************
FROM node:22.14.0-alpine@sha256:9bef0ef1e268f60627da9ba7d7605e8831d5b56ad07487d24d1aa386336d1944 AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat python3 make g++
RUN ln -sf /usr/bin/python3 /usr/bin/python

### APP
# Install dependencies
WORKDIR /app
COPY package.json yarn.lock tsconfig.json ./
COPY vendor ./vendor
COPY types ./types
COPY lib ./lib
COPY configs/app ./configs/app
COPY toolkit/theme ./toolkit/theme
COPY toolkit/utils ./toolkit/utils
COPY toolkit/components/forms/validators/url.ts ./toolkit/components/forms/validators/url.ts
RUN apk add git
RUN --mount=type=cache,id=colossusx-frontend-yarn,target=/usr/local/share/.cache/yarn,sharing=locked yarn --frozen-lockfile --network-timeout 100000


### FEATURE REPORTER
# Install dependencies
WORKDIR /feature-reporter
COPY ./deploy/tools/feature-reporter/package.json ./deploy/tools/feature-reporter/yarn.lock ./
RUN --mount=type=cache,id=colossusx-frontend-yarn,target=/usr/local/share/.cache/yarn,sharing=locked yarn --frozen-lockfile --network-timeout 100000


### ENV VARIABLES CHECKER
# Install dependencies
WORKDIR /envs-validator
COPY ./deploy/tools/envs-validator/package.json ./deploy/tools/envs-validator/yarn.lock ./
RUN --mount=type=cache,id=colossusx-frontend-yarn,target=/usr/local/share/.cache/yarn,sharing=locked yarn --frozen-lockfile --network-timeout 100000

### FAVICON GENERATOR
# Install dependencies
WORKDIR /favicon-generator
COPY ./deploy/tools/favicon-generator/package.json ./deploy/tools/favicon-generator/yarn.lock ./
RUN --mount=type=cache,id=colossusx-frontend-yarn,target=/usr/local/share/.cache/yarn,sharing=locked yarn --frozen-lockfile --network-timeout 100000

### SITEMAP GENERATOR
# Install dependencies
WORKDIR /sitemap-generator
COPY ./deploy/tools/sitemap-generator/package.json ./deploy/tools/sitemap-generator/yarn.lock ./
RUN --mount=type=cache,id=colossusx-frontend-yarn,target=/usr/local/share/.cache/yarn,sharing=locked yarn --frozen-lockfile --network-timeout 100000

### MULTICHAIN CONFIG GENERATOR
# Install dependencies
WORKDIR /multichain-config-generator
COPY ./deploy/tools/multichain-config-generator/package.json ./deploy/tools/multichain-config-generator/yarn.lock ./
RUN --mount=type=cache,id=colossusx-frontend-yarn,target=/usr/local/share/.cache/yarn,sharing=locked yarn --frozen-lockfile --network-timeout 100000

### ESSENTIAL DAPPS CHAINS CONFIG GENERATOR
# Install dependencies
WORKDIR /essential-dapps-chains-config-generator
COPY ./deploy/tools/essential-dapps-chains-config-generator/package.json ./deploy/tools/essential-dapps-chains-config-generator/yarn.lock ./
RUN --mount=type=cache,id=colossusx-frontend-yarn,target=/usr/local/share/.cache/yarn,sharing=locked yarn --frozen-lockfile --network-timeout 100000

### llms.txt GENERATOR
# Install dependencies
WORKDIR /llms-txt-generator
COPY ./deploy/tools/llms-txt-generator/package.json ./deploy/tools/llms-txt-generator/yarn.lock ./
RUN --mount=type=cache,id=colossusx-frontend-yarn,target=/usr/local/share/.cache/yarn,sharing=locked yarn --frozen-lockfile --network-timeout 100000


